title: Adrià Baró Biosca # your name (or website title) here
logo: "/images/logo_black.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Soon to be graduated mechanical engineer with professional experience. Focused in Mechanical Design and
  Product Development. 
  <br><br>
  On August I will start writing my thesis within the field of Robust Design, field which I started exploring with my Bachelor's Thesis and I am keen on continuing "digging into" it. 
  <br><br>
  <a href="https://www.linkedin.com/in/adriabaro/">View My LinkedIn Profile</a>
  <br><br>
  Thank you for your visiting this page.<br>
  Total visits:
  <div id="sfcq641b5yy7tukdprqbtlsgel82sq3tbzp"></div><script type="text/javascript" src="https://counter1.stat.ovh/private/counter.js?c=q641b5yy7tukdprqbtlsgel82sq3tbzp&down=async" async></script><noscript><a href="https://www.freecounterstat.com" title="website counter"><img src="https://counter1.stat.ovh/private/freecounterstat.php?c=q641b5yy7tukdprqbtlsgel82sq3tbzp" border="0" title="website counter" alt="website counter"></a></noscript>
theme: jekyll-theme-minimal
