title: Adrià Baró Biosca # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here

<html><style>
    .image {
        width: 100%;
        height: auto;
        background: url("images/logo_black.png") no-repeat;
        display: inline-block;
    }
    .image:hover {
        background: url("images/logo.png") no-repeat;
    }
</style><\html>
<a href="#">
<img src="/images/logo.png?raw=true" 
onmouseover="this.src='/images/logo_black.png?raw=true'"
onmouseout="this.src='/images/logo.png?raw=true'"
border="0" alt=""/></a>

description: > # your text below (remove <br> elements if you don't need line breaks)
  Recently graduated mechanical engineer with professional experience. Focused in Mechanical Design and
  Product Development.
  <br><br>
  Currently writing my Master thesis in collaboration with ________ within the field of ________.
  <br><br>
  <a href="https://www.linkedin.com/in/adriabaro/">View My LinkedIn Profile</a>
  <br><br>
  Thank you for your visiting this page:
  <div id="sfcq641b5yy7tukdprqbtlsgel82sq3tbzp"></div><script type="text/javascript" src="https://counter1.stat.ovh/private/counter.js?c=q641b5yy7tukdprqbtlsgel82sq3tbzp&down=async" async></script><noscript><a href="https://www.freecounterstat.com" title="website counter"><img src="https://counter1.stat.ovh/private/freecounterstat.php?c=q641b5yy7tukdprqbtlsgel82sq3tbzp" border="0" title="website counter" alt="website counter"></a></noscript>
theme: jekyll-theme-minimal
