title: Adrià Baró Biosca # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Recently graduated mechanical engineer with professional experience. Focused in Mechanical Design and
  Product Development.
  <br><br>
  Currently writing my Master thesis in collaboration with ________ within the field of ________.
  <br><br>
  <a href="https://www.linkedin.com/in/adriabaro/">View My LinkedIn Profile</a> 
  <div id="sfcqxx1x5wactwfbecn3g72zr1lz5t2dsl8"></div><script type="text/javascript" src="https://counter1.stat.ovh/private/counter.js?c=qxx1x5wactwfbecn3g72zr1lz5t2dsl8&down=async" async></script><noscript><a href="https://www.freecounterstat.com" title="hit counter"><img src="https://counter1.stat.ovh/private/freecounterstat.php?c=qxx1x5wactwfbecn3g72zr1lz5t2dsl8" border="0" title="hit counter" alt="hit counter"></a></noscript>
theme: jekyll-theme-minimal
